version: "3.7"

services:

    redis:
        image: redis
        container_name: redis-cache
        ports:
            - 6379:6379


    database:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
                MYSQL_DATABASE: distribute-cache
                MYSQL_ROOT_PASSWORD: root
                MYSQL_ROOT_USER: root
        ports:
            - 3306:3306
        container_name: database
        volumes:
              - ~/docker/mysql-data:/var/lib/mysql


    instance1:
        image: distribute-cache-service:latest
        ports:
            - 8080:8081
        container_name: instance1
        depends_on:
            - database
            - redis
